# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install pytest coverage
    - name: Install dependencies
      run: |
        cd 3_lab/coverage_io/
        pytest test.py -v
    - name: Generate Report
      run: |
        cd 3_lab/coverage_io/
        coverage run -m unittest -v
        coverage xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: 3_lab/coverage_io/ 
